tuttleofx/TuttleOFX

- cmake/FindNumpy.cmake
- libraries/tuttle/CMakeLists.txt
- libraries/tuttle/src/tuttle/host/InputBufferWrapper.i
- libraries/tuttle/src/tuttle/host/OutputBufferWrapper.i
- libraries/tuttle/src/tuttle/host/attribute/Image.i
> CMake: numpy is an optional dependency

- .gitmodules
- CMakeLists.txt
- cmake/FindavTranscoder.cmake
- plugins/image/io/AudioVideo/CMakeLists.txt
- plugins/image/io/AudioVideo/src/common/util.cpp
- plugins/image/io/AudioVideo/src/common/util.hpp
- plugins/image/io/AudioVideo/src/reader/AVReaderDefinitions.hpp
- plugins/image/io/AudioVideo/src/reader/AVReaderPlugin.cpp
- plugins/image/io/AudioVideo/src/reader/AVReaderPlugin.hpp
- plugins/image/io/AudioVideo/src/reader/AVReaderPluginFactory.cpp
- plugins/image/io/AudioVideo/src/reader/AVReaderProcess.tcc
- plugins/image/io/AudioVideo/src/swscale/SwscaleProcess.cpp
- plugins/image/io/AudioVideo/src/swscale/SwscaleProcess.hpp
- plugins/image/io/AudioVideo/src/writer/AVWriterDefinitions.hpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPlugin.cpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPlugin.hpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPluginFactory.cpp
- plugins/image/io/AudioVideo/src/writer/AVWriterProcess.tcc
* Up avtranscoder to v0.5.1
* Set log level of avreader and avwriter to QUIET
* Move avtranscoder submodule with AudioVideo plugin
* Deploy ffmpeg libraries if avTranscoder is built
> Updates for AudioVideo plugin

- libraries/tuttle/src/tuttle/host/ImageEffectNode.cpp
- libraries/tuttle/src/tuttle/host/graph/ProcessGraph.cpp
- libraries/tuttle/src/tuttle/host/memory/MemoryCache.cpp
- libraries/tuttle/src/tuttle/host/memory/MemoryPool.cpp
- libraries/tuttle/src/tuttle/host/memory/MemoryPool.hpp
> Fix memory pool/cache management

- plugins/image/io/AudioVideo/CMakeLists.txt
- plugins/image/io/AudioVideo/src/common/util.hpp
- plugins/image/io/AudioVideo/src/reader/AVReaderPlugin.cpp
- plugins/image/io/AudioVideo/src/reader/AVReaderPluginFactory.cpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPlugin.cpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPlugin.hpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPluginFactory.cpp
- plugins/image/io/AudioVideo/src/writer/AVWriterProcess.tcc
> AudioVideo: up avtranscoder to v0.5.3

- plugins/image/process/color/ColorTransfer/src/ColorTransferPlugin.cpp
> ColorTransfer: do not try to get roi of srcRef clip if it's not connected

- libraries/tuttle/src/tuttle/host/graph/ProcessGraph.cpp
- plugins/image/io/AudioVideo/src/common/util.cpp
- plugins/image/io/AudioVideo/src/common/util.hpp
- plugins/image/io/AudioVideo/src/mainEntry.cpp
- plugins/image/io/AudioVideo/src/reader/AVReaderDefinitions.hpp
- plugins/image/io/AudioVideo/src/reader/AVReaderPlugin.cpp
- plugins/image/io/AudioVideo/src/reader/AVReaderPluginFactory.cpp
- plugins/image/io/AudioVideo/src/writer/AVWriterDefinitions.hpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPlugin.cpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPlugin.hpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPluginFactory.cpp
* Clean AudioVideo + fixes
* Need to review especially last commit: ProcessGraph, call begin/endSequence foreach plugin only one time (fix issue #399).
> AudioVideo: fixes

- libraries/tuttle/src/tuttle/common/utils/Formatter.cpp
- libraries/tuttle/src/tuttle/common/utils/Formatter.hpp
- libraries/tuttle/src/tuttle/host/Core.cpp
Also fix compilation warning.
Fix #391
Fix #410
> Fix log printed twice

- plugins/image/generator/Text/src/TextPluginFactory.cpp
- plugins/image/generator/Text/src/TextProcess.tcc
> Text plugin: fix computation when node does not find any font

- README.md
The goal is to show to other people, what will be the next development.
> README: add badge to check which issues are ready

- applications/sam/common/samDoUtils.py
- applications/sam/common/samUtils.py
- applications/sam/sam_do.py
- libraries/tuttle/src/tuttle/common/utils/Formatter.cpp
- libraries/tuttle/src/tuttle/host/ComputeOptions.hpp
> sam do: set host log level

- .travis.yml
- tools/travis/deploy.sh
> Travis: fix binaries from deploy service

- tools/travis/deploy.sh
> Travis: fix deploy of linux jobs

- applications/sam/common/samDoUtils.py
- applications/sam/common/samUtils.py
- applications/sam/sam_do.py
> sam do: fix read/write with folder

- applications/sam/common/samUtils.py
- applications/sam/sam_ls.py
- applications/sam/sam_mv.py
* mv: fix python error when logging if item is not a sequence
* ls: fix if try to display a given sequence which does not exist
* all sam tools: set default log level to warning
> sam ls/mv: fix some errors

- applications/example/pythonBinding/demo_burn_timecode.py
- applications/example/pythonBinding/demo_constant_merge.py
- applications/example/pythonBinding/demo_progress_handle.py
- applications/example/pythonBinding/viewer.py
- applications/sam/sam_do.py
- applications/script/seqToMovie.py
- libraries/tuttle/pyTest/compute/testComputeTime.py
- libraries/tuttle/src/tuttle/common/utils/Formatter.cpp
- libraries/tuttle/src/tuttle/common/utils/Formatter.hpp
- libraries/tuttle/src/tuttle/host/ComputeOptions.hpp
- libraries/tuttle/src/tuttle/host/thumbnail/ThumbnailDiskCache.cpp
Fix #458
Remove EVerboseLevel.
Warning: will break the python API!
> host: keep one enum to define verbose level

- plugins/image/display/ColorCubeViewer/src/ColorCubeViewerPluginFactory.cpp
- plugins/image/generator/Text/src/TextPluginFactory.cpp
- plugins/image/process/color/ColorTransform/src/ColorTransformPluginFactory.cpp
- plugins/image/process/color/Colorspace/src/ColorSpacePluginFactory.cpp
- plugins/image/process/color/Gamma/src/GammaPluginFactory.cpp
- plugins/image/process/filter/FloodFill/src/FloodFillPluginFactory.cpp
- plugins/image/process/filter/Thinning/src/ThinningPluginFactory.cpp
- plugins/param/analysis/Diff/src/DiffPluginFactory.cpp
- plugins/param/analysis/ImageStatistics/src/ImageStatisticsPluginFactory.cpp
> Add missing plugin description

- applications/sam/sam_do.py
> sam do: enhancements

- plugins/image/io/Raw/src/reader/RawReaderDefinitions.hpp
- plugins/image/io/Raw/src/reader/RawReaderPlugin.cpp
- plugins/image/io/Raw/src/reader/RawReaderPlugin.hpp
- plugins/image/io/Raw/src/reader/RawReaderPluginFactory.cpp
- plugins/image/io/Raw/src/reader/RawReaderProcess.hpp
- plugins/image/io/Raw/src/reader/RawReaderProcess.tcc
To do:
* strange value of _paramShutter.  
https://github.com/tuttleofx/TuttleOFX/blob/develop/plugins/image/io/Raw/src/reader/RawReaderPlugin.cpp#L130
* 3 parameters to manually set white balance => Kelvin.  
It depends on the colorspace... Not easy to compute.
> rawreader: dev white balance

- CMakeLists.txt
- USAGE.md
- libraries/tuttle/src/tuttle/host/ofx/OfxhPluginCache.cpp
> Host: add a default path to OFX plugins

- plugins/image/io/AudioVideo/src/mainEntry.cpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPlugin.cpp
- plugins/image/io/AudioVideo/src/writer/AVWriterPlugin.hpp
- plugins/image/io/AudioVideo/src/writer/AVWriterProcess.tcc
> AudioVideo: up to v4.7

- USAGE.md
> USAGE.md: added a section to override path to plugin cache

- USAGE.md
- libraries/tuttle/src/tuttle/common/system/system.hpp
> Fix path to the plugin cache

- plugins/image/io/AudioVideo/src/mainEntry.cpp
* Update avtranscoder submodule to v0.9.4.
* See avtranscoder release note:
https://github.com/avTranscoder/avTranscoder/releases/tag/v0.9.4
* Fix #544
> AudioVideo: up to v4.8
